apiVersion: v1
kind: Secret
metadata:
  namespace: outline-kb
  name: outline-env
type: Opaque
data:
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  GOOGLE_CLIENT_ID: 
  GOOGLE_CLIENT_SECRET: 
  MINIO_ACCESS_KEY: 
  MINIO_SECRET_KEY: 
  SECRET_KEY: 
  SLACK_APP_ID: 
  SLACK_KEY: 
  SLACK_SECRET: 
  SLACK_VERIFICATION_TOKEN: 
  SMTP_PASSWORD: 
  UTILS_SECRET: 
